# Generated by Django 2.2.9 on 2020-05-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст коментария'),
        ),
    ]
